### ISSUE TITLE
Cursorline transparency

### ISSUE THREAD

**Issue by Kyle-Thompson** [miyakogi/seiya.vim#1]
Since I have `set cursorline` in my vimrc I end up with a nice, transparent background but a solid bar on my current line. It would be great if the cursorline could also be transparent to remain consistent with the rest of the system.

**Comment by miyakogi** [comment]
If cursorline is transparent, it's same as `set nocursorline`.
Please manually disable `cursorline` option, sorry.

**Comment by Kyle-Thompson** [comment]
There's no way to have partial transparency like you can with the background? It would be the same as nocursorline if my transparency is at 100%, which it isn't.

**Comment by miyakogi** [comment]
Always this plugin changes transparency 100%.
If your background looks partially transparent, you are looking the terminal's background, not vim's background.
